name: Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "needs-triage"]
# assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the sections below to help us understand and reproduce the issue.

  - type: checkboxes
    id: preliminary-checks
    attributes:
      label: Preliminary Checks
      description: Please confirm the following before submitting your bug report
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported before
          required: true
        - label: I have checked the documentation and FAQ for potential solutions
          required: true
        - label: I am using the latest version of the software
          required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "The application crashes when..."
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the bug
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
      value: |
        1. 
        2. 
        3. 
        4. 
    validations:
      required: true

  - type: textarea
    id: error-messages
    attributes:
      label: Error Messages/Logs
      description: Include any error messages, stack traces, or relevant log output
      placeholder: "Paste error messages or logs here..."
      render: shell
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical - Application unusable/crashes
        - High - Major functionality broken
        - Medium - Some functionality impacted
        - Low - Minor issue/cosmetic problem
    validations:
      required: true