name: Auto apply black

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          ref: ${{ github.head_ref }}

      - name: Set up Python VM
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Black
        run: pip install black

      - name: Install Black for jupyter notebooks
        run: pip install "black[jupyter]"

      - name: Check formatting
        id: black_check
        run: |
          black --check .
        continue-on-error: true

      - name: Applying black
        if: steps.black_check.outcome == 'failure'
        run: | 
          black . 
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git commit -am "Auto-format code with Black"
          git push
