# Using the package with Plotly


## Line charts
### Single line chart

```{python}
# | label: line-charts-1
# | eval: true
# | output: false

import plotly.graph_objects as go

from afcharts.pio_template import pio

# Set default theme
pio.templates.default = "afcharts"

# Load the gapminder dataset from plotly.express
from plotly.express.data import gapminder

df = gapminder().query("country == 'United Kingdom'")

# Create figure
fig = go.Figure()

# Add a trace
fig.add_trace(
    go.Scatter(
        x=df["year"],
        y=df["lifeExp"],
        mode="lines",
        name="United Kingdom",
        text=df["country"],
    )
)

# Add label at the last point
last_year = df["year"].max()
last_lifeExp = df[df["year"] == last_year]["lifeExp"].values[0]

# Update layout
fig.update_layout(
    xaxis=dict(
        showgrid=False,  # Hide x-axis grid lines
        dtick=10,  # Show ticks every 10 units
        range=[1950, 2010],
    ),
    yaxis=dict(
        range=[0, 82],
        tickmode="linear",
        dtick=10,  # Show ticks every 10 units
    ),
    showlegend=False,
    height=400,
    margin=dict(r=40),
)

fig.show()
```

<div class="chart-title">Living Longer</div>
<div class="chart-subtitle">Life expectancy in the United Kingdom 1952 to 2007</div>
<div class="chart" aria-describedby="linechart-1-desc">

```{python}
#| echo: false

fig.show()

```

</div>
<div class="chart-source">Source: Gapminder</div>
<div class="chart-alt" id="linechart-1-desc">
This line chart uses the afcharts theme. There are pale grey grid lines extending from the y axis, and there is a thicker dark blue line representing the data.
</div>

### Line chart with duo palette

```{python}
# | label: line-charts-2
# | eval: true
# | output: false

import plotly.express as px
import plotly.graph_objects as go

from afcharts.pio_template import pio
from afcharts.af_colours import get_af_colours

# Get the duo colour palette
duo = get_af_colours("duo")

# Set default theme
pio.templates.default = "afcharts"

# Load the gapminder dataset from plotly.express
from plotly.express.data import gapminder

df = gapminder()
df = df[df["country"].isin(["United Kingdom", "China"])]

# Create figure
fig = go.Figure()

# Add a trace for each continent
for i, country in enumerate(df["country"].unique()):
    df_country = df[df["country"] == country]

    fig.add_trace(
        go.Scatter(
            x=df_country["year"],
            y=df_country["lifeExp"],
            mode="lines",
            name=country,
            text=df_country["country"],
            line=dict(color=duo[i % len(duo)]),
        )
    )

    # Add label at the last point
    last_year = df_country["year"].max()
    last_lifeExp = df_country[df_country["year"] == last_year]["lifeExp"].values[0]

    fig.add_annotation(
        dict(
            x=last_year,
            y=last_lifeExp,
            text=country,
            showarrow=False,
            xanchor="left",
            yanchor="middle",
            bgcolor="white",  # Add a white background
        )
    )

# Update layout
fig.update_layout(
    xaxis=dict(
        showgrid=False,  # Hide x-axis grid lines
        dtick=10,  # Show ticks every 10 units
        range=[1950, 2010],
    ),
    yaxis=dict(
        range=[0, 82],
        tickmode="linear",
        dtick=10,  # Show ticks every 10 units
    ),
    showlegend=False,
    height=350,
    margin=dict(r=120),
)

fig.show()
```

<div class="chart-title">Living Longer</div>
<div class="chart-subtitle">Life expectancy in the United Kingdom and China 1952 to 2007</div>
<div class="chart" aria-describedby="linechart-2-desc">

```{python}
#| echo: false

fig.show()

```

</div>
<div class="chart-source">Source: Gapminder</div>
<div class="chart-alt" id="linechart-2-desc">
This line chart uses the afcharts theme and there are thin pale grey lines extending from the y axis. There are two thicker lines showing the life expectancy in the UK and China over time. The line colours are from the Analysis Function 'duo' palette - dark blue for China and orange for the UK, with labels for each line on the right hand side.
</div>

Legends should be avoided unless absolutely necessary, as these usually rely on using colour to match labels to data. More information can be found in the Analysis Function [charts guidance](https://analysisfunction.civilservice.gov.uk/policy-store/data-visualisation-charts/#section-11). It is best practice to label lines directly.

## Bar charts

```{python}
# | eval: true
# | output: false

import plotly.graph_objects as go

from afcharts.pio_template import pio

# Set default theme
pio.templates.default = "afcharts"

# Load the gapminder dataset from plotly.express
from plotly.express.data import gapminder

# Filter for Americas in 2007 and get top 5 by population
df = gapminder().query("year == 2007 & continent == 'Americas'")

top5 = df.nlargest(5, "pop")

fig = go.Figure()

fig.add_trace(
    go.Bar(
        x=top5["country"],
        y=top5["pop"] / 1e6,  # Convert to millions
    )
)

# Update layout
fig.update_layout(
    height=420
)

fig.show()

```

<div class="chart-title">The U.S.A. is the most populous country in the Americas</div>
<div class="chart-subtitle">Population of countries in the Americas (millions), 2007</div>
<div class="chart" aria-describedby="barchart-1-desc">

```{python}
#| echo: false

fig.show()

```

</div>
<div class="chart-source">Source: Gapminder</div>
<div class="chart-alt" id="barchart-1-desc">
This bar chart uses the afcharts theme, and shows the populations of the five most populous countries in the Americas. Each bar is dark blue and labelled by country underneath. All text is black in a sans serif font. Pale grey grid lines extend out from the y axis.
</div>

### Grouped bar chart

```{python}
# | eval: true
# | output: false

import plotly.graph_objects as go

from afcharts.pio_template import pio
from afcharts.af_colours import get_af_colours

# Set default theme
pio.templates.default = "afcharts"

# Get the duo colour palette
duo = get_af_colours("duo")

# Load the gapminder dataset from plotly.express
from plotly.express.data import gapminder

df = gapminder().query(
    "year in [1967, 2007] & country in ['United Kingdom', 'Ireland', 'France', 'Belgium']"
)

fig = go.Figure()
# Add a bar trace for each year
for i, year in enumerate(sorted(df["year"].unique())):
    df_year = df[df["year"] == year]
    fig.add_trace(
        go.Bar(
            x=df_year["country"],
            y=df_year["lifeExp"],
            name=str(year),
            marker_color=duo[i % len(duo)],
        )
    )

# Update layout
fig.update_layout(
    barmode="group",
    height=420,
    legend=dict(
        orientation="h",
        yanchor="top",
        y=-0.2,
        xanchor="center",
        x=0.5
    ),
)

fig.show()
```

<div class="chart-title">Living longer</div>
<div class="chart-subtitle">Life expectancy (years) in 1967 and 2007</div>
<div class="chart" aria-describedby="barchart-2-desc">

```{python}
#| echo: false

fig.show()

```

</div>
<div class="chart-source">Source: Gapminder</div>
<div class="chart-alt" id="barchart-2-desc">
This grouped bar chart uses the afcharts theme. It shows the life expectancy in 1967 and 2007 for four countries, which are displayed on the x axis. For each country there are two bars. The bar colours are from the Analysis Function 'duo' palette - dark blue for 1967 and orange for 2007, denoted by a legend at the bottom of the chart.
</div>

### Stacked bar chart

Caution should be taken when producing stacked bar charts. They can quickly become difficult to interpret if plotting non part-to-whole data, and/or if plotting more than two categories per stack. First and last categories in the stack will always be easier to compare across bars than those in the middle. Think carefully about the story you are trying to tell with your chart.

```{python}
# | eval: true
# | output: false

import pandas as pd
import plotly.graph_objects as go
from afcharts.pio_template import pio

from afcharts.af_colours import get_af_colours

# Get the duo colour palette
duo = get_af_colours("duo")

# Set default theme
pio.templates.default = "afcharts"

# Load the gapminder dataset from plotly.express
from plotly.express.data import gapminder

df = gapminder().query("year == 2007")

# Create life expectancy groups
df["lifeExpGrouped"] = pd.cut(
    df["lifeExp"],
    bins=[0, 75, float("inf")],
    labels=["Under 75", "75 and over"]
)

# Group by continent and life expectancy group
grouped = (
    df.groupby(["continent", "lifeExpGrouped"], observed=True)
    .size()
    .reset_index(name="n_countries")
)

# Pivot to get proportions
pivot_df = grouped.pivot(
    index="continent", columns="lifeExpGrouped", values="n_countries"
).fillna(0)
pivot_df["total"] = pivot_df.sum(axis=1)
pivot_df["percent of Under 75"] = pivot_df["Under 75"] / pivot_df["total"]
pivot_df["percent of 75 and over"] = pivot_df["75 and over"] / pivot_df["total"]

categories = ["Under 75", "75 and over"]

fig = go.Figure()

# Add a bar trace for each category
for i, category in enumerate(categories):
    percent_col = f"percent of {category}"
    life_exp_data = pivot_df[[percent_col]]

    fig.add_trace(
        go.Bar(
            x=life_exp_data.index,
            y=life_exp_data[percent_col],
            name=str(category),
            marker_color=duo[i % len(duo)],
        )
    )

# Update layout
fig.update_layout(
    barmode="stack",
    height=420,
    yaxis=dict(tickformat=".0%"),
    legend=dict(
        title="Life Expectancy",
        orientation="h",
        yanchor="top",
        y=-0.2,
        xanchor="center",
        x=0.5,
    ),
)

fig.show()

```

<div class="chart-title">How life expectancy varies across continents</div>
<div class="chart-subtitle">Percentage of countries by life expectancy band, 2007</div>
<div class="chart" aria-describedby="barchart-stack-desc">

```{python}
#| echo: false

fig.show()

```

</div>
<div class="chart-source">Source: Gapminder</div>
<div class="chart-alt" id="barchart-stack-desc">
This stacked bar chart uses the afcharts theme and shows the proportions of countries with a life expectancy over and under 75 by continent. The continents are listed along the x axis, with the y axis labelled between 0% and 100%. The colours for the bar segments are from the Analysis Function 'duo' palette - dark blue for under 75 and orange for over 75, denoted by a legend at the bottom of the chart. There is whitespace between each bar.
</div>


## Histograms

```{python}
# | eval: true
# | output: false

import plotly.graph_objects as go

from afcharts.pio_template import pio

# Set default theme
pio.templates.default = "afcharts"

# Load the gapminder dataset from plotly.express
from plotly.express.data import gapminder

# Filter for year 2007
df = gapminder().query("year == 2007")

fig = go.Figure()

fig.add_trace(
    go.Histogram(
        x=df["lifeExp"],
        xbins=dict(start=int(df["lifeExp"].min()), end=int(df["lifeExp"].max()) + 5, size=5),
    )
)

# Update layout
fig.update_layout(
    height=420,
    yaxis=dict(title="Number of countries"),
)

fig.show()

```

<div class="chart-title">How life expectancy varies</div>
<div class="chart-subtitle">Distribution of life expectancy, 2007</div>
<div class="chart" aria-describedby="histogram-1-desc">

```{python}
#| echo: false

fig.show()

```

</div>
<div class="chart-source">Source: Gapminder</div>
<div class="chart-alt" id="histogram-1-desc"> This histogram uses the afcharts theme, and shows the distribution of life expectancy across countries in 2007. The x-axis shows life expectancy in 5-year bins, and the y-axis shows the number of countries. The bars are dark blue with white edges separating each bin. Pale grey grid lines extend out from the y-axis. </div>

## Scatterplots

```{python}
# | eval: true
# | output: false
import plotly.graph_objects as go

from afcharts.pio_template import pio

# Set default theme
pio.templates.default = "afcharts"

# Load the gapminder dataset from plotly.express
from plotly.express.data import gapminder

df = gapminder().query("year == 2007")

fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=df["gdpPercap"],
        y=df["lifeExp"],
        mode="markers",
    )
)

# Axes should start from 0
fig.update_yaxes(rangemode="tozero")

# Update layout
fig.update_layout(
    xaxis=dict(
        title="GDP per capita ($US, inflation-adjusted)",
    ),
    yaxis=dict(title="Life Expectancy (years)"),
    height=420,
)

fig.show()
```

<div class="chart-title">The relationship between GDP and Life Expectancy is complex</div>
<div class="chart-subtitle">GDP and Life Expectancy for all countries, 2007</div>
<div class="chart" aria-describedby="scatter-desc">

```{python}
#| echo: false

fig.show()

```

</div>
<div class="chart-source">Source: Gapminder</div>
<div class="chart-alt" id="scatter-desc">
This scatterplot uses the afcharts theme, and shows life expectancy against GDP per capita for 142 countries in 2007. Thin pale grey lines extend out from the x and y axis labels, forming a grid. The data points are plotted as dark blue circles. Both axes are labeled in black using a sans serif font.
</div>

## Small multiples
```{python}
# | eval: true
# | output: false

import plotly.graph_objects as go
from plotly.subplots import make_subplots

from afcharts.pio_template import pio

from afcharts.af_colours import get_af_colours

# Get the categorical colour palette
categorical = get_af_colours("categorical")

# Set default theme
pio.templates.default = "afcharts"

# Load the gapminder dataset from plotly.express
from plotly.express.data import gapminder

df = gapminder()

# Filter out Oceania and aggregate population by continent and year
df_grouped = (
    df[df["continent"] != "Oceania"]
    .groupby(["continent", "year"], observed=True)["pop"].sum()
    .reset_index()
)

# Define the continents to plot
continents = df_grouped["continent"].unique()

# Create a 2x2 subplot layout
fig = make_subplots(rows=2, cols=2, subplot_titles=continents, shared_yaxes=True)

# Add area traces for each continent
for i, continent in enumerate(continents):
    row = i // 2 + 1
    col = i % 2 + 1
    data = df_grouped[df_grouped["continent"] == continent]
    fig.add_trace(
        go.Scatter(
            x=data["year"],
            y=data["pop"],
            fill="tozeroy",
            mode="none",
            name=continent,
            showlegend=False,
            fillcolor=categorical[i % len(categorical)],
        ),
        row=row,
        col=col,
    )


# Customize axes
fig.update_xaxes(showgrid=False)
fig.update_yaxes(
    range=[0, 4.1e9],
    tickvals=[0, 2e9, 4e9],
    ticktext=["0", "2bn", "4bn"],
    showgrid=True,
)

# Update layout
fig.update_layout(
    height=550,
    margin=dict(t=30),
)

fig.show()

```

<div class="chart-title">Asia's rapid growth</div>
<div class="chart-subtitle">Population growth by continent, 1952-2007</div>
<div class="chart" aria-describedby="small-multiples-desc">

```{python}
#| echo: false

fig.show()

```

</div>
<div class="chart-source">Source: Gapminder</div>
<div class="chart-alt" id="small-multiples-desc">
This chart uses the afcharts theme. It contains four subplots in a two by two grid showing how the populations of four continents have changed over time. Each subplot is labelled with the continent. The subplots have a common y axis, with no values on the x axis to facilitate for a simple comparison of the relative values. Each subplot is filled with a different colour from the Analysis Function categorical colour palette to be distinct from other subplots.
</div>

## Pie charts
```{python}
# | eval: true
# | output: false

import pandas as pd
import plotly.graph_objects as go

from afcharts.pio_template import pio

from afcharts.af_colours import get_af_colours

# Get the duo colour palette
duo = get_af_colours("duo")

# Set default theme
pio.templates.default = "afcharts"

# Load the gapminder dataset from plotly.express
from plotly.express.data import gapminder

df = gapminder().query("continent == 'Europe' and year == 2007")

# Create life expectancy groups
df["lifeExpGrouped"] = pd.cut(
    df["lifeExp"],
    bins=[0, 75, float("inf")],
    labels=["Under 75", "75 and over"]
)

# Count number of countries in each group
group_counts = df["lifeExpGrouped"].value_counts().sort_index()

fig = go.Figure(
    data=[
        go.Pie(
            values=group_counts.values,
            labels=group_counts.index,
            marker=dict(colors=duo, line=dict(color="white", width=2)),
            sort=False,
            textinfo="label+percent",
            textposition="inside",
            texttemplate="%{label}<br>(%{percent:.0%})",
        )
    ]
)

# Update layout
fig.update_layout(
    height=400,
    showlegend=False
)

fig.show()
```

<div class="chart-title">How life expectancy varies in Europe</div>
<div class="chart-subtitle">Percentage of countries by life expectancy band, 2007</div>
<div class="chart" aria-describedby="pie-desc">

```{python}
#| echo: false

fig.show()

```

</div>
<div class="chart-source">Source: Gapminder</div>
<div class="chart-alt" id="pie-desc">
This pie chart uses the afcharts theme, showing the proportions of European countries with a life expectancy under and over 75. The segment colours are from the Analysis Function categorical palette, with the smaller under 75 segment in dark blue, and the larger over 75 segment in orange. This is indicated by a legend to the right of the pie chart. There is whitespace separating the segments from each other.
</div>

## Focus charts
```{python}
# | eval: true
# | output: false

import plotly.graph_objects as go

from afcharts.pio_template import pio

from afcharts.af_colours import get_af_colours

# Get the focus colour palette
focus = get_af_colours("focus")

# Set default theme
pio.templates.default = "afcharts"

# Load the gapminder dataset from plotly.express
from plotly.express.data import gapminder

df = gapminder().query("year == 2007 & continent == 'Americas'")

top5 = df.nlargest(5, "pop")

colours = {
    country: focus[0 if country == "Brazil" else 1]
    for country in top5["country"].unique()
}

# Map colors to bar order
bar_colours = [colours[country] for country in top5["country"]]

fig = go.Figure()

fig.add_trace(
    go.Bar(
        x=top5["country"],
        y=top5["pop"],  # Repeat the category name for each x value
        marker_color=bar_colours,
    )
)

# Update layout
fig.update_layout(
    height=420
)

fig.show()
```

<div class="chart-title">Brazil has the second highest population in the Americas</div>
<div class="chart-subtitle">Population of countries in the Americas (millions), 2007</div>
<div class="chart" aria-describedby="focus-desc">

```{python}
#| echo: false

fig.show()

```

</div>
<div class="chart-source">Source: Gapminder</div>
<div class="chart-alt" id="focus-desc">
This bar chart uses the afcharts theme, and shows the populations of five countries of the Americas in descending order. The country names are given on the x axis, with all chart text in black in a sans serif font. Four of the bars on the chart are light grey, and the bar for Brazil is filled in dark blue to highlight it.
</div>

## Annotations

Labelling your chart is often preferable to using a legend, as often this relies on a user matching the legend to the data using colour alone.

You can add an annotation anywhere on a chart using the `annotate()` method. This is demonstrated above in [Line chart with duo palette](#line-chart-with-duo-palette), which directly labels each line. Note that black text has been used for the labels, as this ensures sufficient contrast against the white background.

To add value labels to bars in a bar chart, use the `text` argument of `go.Bar()`. In the example below, the population values are added as white text labels inside the bars.

```{python}
# | output: false

import plotly.graph_objects as go

from afcharts.pio_template import pio

# Set default theme
pio.templates.default = "afcharts"

# Load the gapminder dataset from plotly.express
from plotly.express.data import gapminder

# Filter for Americas in 2007 and get top 5 by population
df = gapminder().query("year == 2007 & continent == 'Americas'")

top5 = df.nlargest(5, "pop")

fig = go.Figure()

x = top5["country"]
y = top5["pop"] / 1e6  # millions

fig.add_trace(
    go.Bar(
        x=x,
        y=y,
        text=round(y, 2),
    )
)

# Update layout
fig.update_layout(height=420)

fig.show()

```

<div class="chart-title">The U.S.A. is the most populous country in the Americas</div>
<div class="chart-subtitle">Population of countries in the Americas (millions), 2007</div>
<div class="chart" aria-describedby="barchart-annotated-desc">

```{python}
#| echo: false

fig

```

</div>
<div class="chart-source">Source: Gapminder</div>
<div class="chart-alt" id="barchart-annotated-desc">
This bar chart uses the afcharts theme, and shows the populations of the five most populous countries in the Americas. Each bar is dark blue and labelled by country underneath. White text labels are added inside each bar showing the population value in millions. Pale grey grid lines extend out from the y axis.
</div>

## Other customisations
### Sorting a bar chart

To control the order of bars in a bar chart, sort the data object before plotting. For Pandas data frames, you can use the `.sort_values()` method. Pass the name or list of names that you would like to sort by and specify whether ascending (True, default) or descending (False). In this below example, the data is sorted on `pop` and ascending is set to `True` so that the bars are displayed in ascending order of population.


```{python}
# | output: false

import plotly.graph_objects as go

from afcharts.pio_template import pio

# Set default theme
pio.templates.default = "afcharts"

# Load the gapminder dataset from plotly.express
from plotly.express.data import gapminder

# Filter for Americas in 2007 and get top 5 by population
df = gapminder().query("year == 2007 & continent == 'Americas'")

top5 = df.nlargest(5, "pop").sort_values("pop", ascending=True)

fig = go.Figure()

fig.add_trace(
    go.Bar(
        x=top5["pop"],
        y=top5["country"],
        orientation="h",
    )
)

# Update layout
fig.update_layout(height=420)

fig.show()
```

<div class="chart-title">The U.S.A. is the most populous country in the Americas</div>
<div class="chart-subtitle">Population of countries in the Americas (millions), 2007</div>
<div class="chart" aria-describedby="sortbar-desc">

```{python}
#| echo: false

fig

```

</div>
<div class="chart-source">Source: Gapminder</div>
<div class="chart-alt" id="sortbar-desc">
This bar chart uses the afcharts theme, and shows the populations of the five most populous countries in the Americas, sorted in ascending order by population. Each bar is dark blue and labelled by country underneath. All text is black in a sans serif font. Pale grey grid lines extend out from the y axis.
</div>

### Adding a horizontal or vertical line

To add a horizontal or vertical line across the whole plot, use `add_hline()` or `add_vline()` respectively. Annotating the line can be achieved using `annotation_text` argument. This can be useful to highlight a threshold or average level.  

```{python}
# | output: false

import plotly.graph_objects as go

from afcharts.pio_template import pio

# Set default theme
pio.templates.default = "afcharts"

# Load the gapminder dataset from plotly.express
from plotly.express.data import gapminder

df = gapminder().query("country == 'United Kingdom'")

# Create figure
fig = go.Figure()

# Add a trace
fig.add_trace(
    go.Scatter(
        x=df["year"],
        y=df["lifeExp"],
        mode="lines",
        name="United Kingdom",
        text=df["country"],
    )
)


# Add a dotted horizontal line for 70 years of age
fig.add_hline(
    y=70,
    line_dash="dash",  # dashed line
    line_color="gray",  # gray color
    annotation_text="Age 70",  # label
    annotation_position="top right",
    annotation_font_size=14,
    annotation_font_color="black",
)

# Update layout
fig.update_layout(
    xaxis=dict(
        showgrid=False,  # Hide x-axis grid lines
        dtick=10,  # Show ticks every 10 units
        range=[1950, 2010],
    ),
    yaxis=dict(
        range=[0, 82],
        tickmode="linear",
        dtick=10,  # Show ticks every 10 units
    ),
    showlegend=False,
    height=400,
    margin=dict(r=40),
)

fig.show()

```

<div class="chart-title">Living Longer</div>
<div class="chart-subtitle">Life expectancy in the United Kingdom 1952 to 2007</div>
<div class="chart" aria-describedby="hline-desc">

```{python}
#| echo: false

fig.show()

```

</div>
<div class="chart-source">Source: Gapminder</div>
<div class="chart-alt" id="hline-desc">
This line chart uses the afcharts theme. There are pale grey grid lines extending from the y axis, and there is a thicker dark blue line representing the data. A dotted horizontal line has been added at 70 years of age, with an annotation to label it.
</div>

### Wrapping text

If text is too long, it may be cut off or distort the dimensions of the chart. To avoid this, text can be wrapped to multiple lines using the `textwrap` module. The width argument controls how many characters are allowed on each line before wrapping. See the figure title below for an example.

Alternatively, you can manually add line breaks by inserting `<br>` into the text string to control where the text is wrapped. See the y-axis label in the figure below for an example.

```{python}
# | output: false

import textwrap
import plotly.graph_objects as go

from afcharts.pio_template import pio

# Set default theme
pio.templates.default = "afcharts"

# Load the gapminder dataset from plotly.express
from plotly.express.data import gapminder

df = gapminder().query("year == 2007 & continent == 'Americas'")

top5 = df.nlargest(5, "pop")

fig = go.Figure()

fig.add_trace(
    go.Bar(
        x=top5["country"],
        y=top5["pop"] / 1e6,
    )
)

# Update layout
fig.update_layout(
    title="<br>".join(
        textwrap.wrap(
            "The U.S.A. is the most populous country in the Americas by a wide margin",
            width=40,
        )
    ),  # Plotly does not support \n you must use a <br>
    margin=dict(t=80),  # Increase top margin so the title is not clipped
    yaxis=dict(title="Population<br>in millions"),  # Plotly does not support rotating axis labels
    height=420,
)

fig.show()

```

<div class="chart-title">The U.S.A. is the most populous country in the Americas</div>
<div class="chart-subtitle">Population of countries in the Americas (millions), 2007</div>
<div class="chart" aria-describedby="textwrap-desc">

```{python}
# | echo: false

fig.show()

```

</div>
<div class="chart-source">Source: Gapminder</div>
<div class="chart-alt" id="textwrap-desc">
In this bar chart image, the y-axis label and chart title text have been wrapped onto two lines so that all the text is visible without being cut off.
</div>