# Government Analysis Function colour palettes

**This page is a work in progress**

afcharts provides colour palettes as set out by the [Government Analysis Function](https://analysisfunction.civilservice.gov.uk/policy-store/data-visualisation-colours-in-charts/). 

These palettes have been developed to meet the [Web Content Accessibility Guidelines 2.1 for graphical objects](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html). The colours in the [main palette for categorical data](#main-palette) all have at least a 3:1 colour contrast ratio with white (#ffffff), as well as with adjacent colours in the palette. 


The [main palette](https://best-practice-and-impact.github.io/afcharts/articles/colours.html#main-palette) is the default for discrete colour/fill functions, and the [sequential palette](https://best-practice-and-impact.github.io/afcharts/articles/colours.html#sequential-palette) for continuous colour/fill functions.


## Using afcharts colour palettes

The full list of available palettes can be found by running `afcharts.assets.af_colours`.

### af_colour_values dictionary
```{python}
# | echo: false
import pandas as pd
from afcharts.assets.af_colours import (
    af_colour_values,
    main,
    duo,
    sequential,
    diverging,
)

df = pd.DataFrame(list(af_colour_values.items()), columns=["Name", "Hex Code"])

df["Preview"] = df["Hex Code"].apply(
    lambda x: f'<span style="background-color:{x};padding:5px 20px;display:inline-block;"></span>'
)
from IPython.display import display, HTML

display(HTML(df.to_html(escape=False)))
```

### main palette

The `main` palette should be used with categorical data.
```{python}
#| echo: false
df = pd.DataFrame(main, columns=["Hex Code"])

# Add HTML preview column
df["Preview"] = df["Hex Code"].apply(
    lambda x: f'<span style="background-color:{x};padding:5px 20px;display:inline-block;border:1px solid #000;"></span>'
)

# Display the DataFrame with HTML rendering
display(HTML(df.to_html(escape=False, index=False)))
```


### duo palette
The `duo` palette should be used if only two colours are required as the dark blue and orange colours have the best colour contrast with each other. 

```{python}
#| echo: false
df = pd.DataFrame(duo, columns=["Hex Code"])

# Add HTML preview column
df["Preview"] = df["Hex Code"].apply(
    lambda x: f'<span style="background-color:{x};padding:5px 20px;display:inline-block;border:1px solid #000;"></span>'
)

# Display the DataFrame with HTML rendering
display(HTML(df.to_html(escape=False, index=False)))
```


### sequential palette
The `sequential` colour palette should be used for data where the order has some meaning.
There is also a reverse alternative `sequential_minus`.
```{python}
#| echo: false
df = pd.DataFrame(sequential, columns=["Value", "Hex Code"])

# Add HTML preview column
df["Preview"] = df["Hex Code"].apply(
    lambda x: f'<span style="background-color:{x};padding:5px 40px;display:inline-block;border:1px solid #000;"></span>'
)

# Display the DataFrame with HTML rendering
display(HTML(df.to_html(escape=False, index=False)))
```

### diverging palette
```{python}
#| echo: false
df = pd.DataFrame(diverging, columns=["Value", "Hex Code"])

# Add HTML preview column
df["Preview"] = df["Hex Code"].apply(
    lambda x: f'<span style="background-color:{x};padding:5px 40px;display:inline-block;border:1px solid #000;"></span>'
)

# Display the DataFrame with HTML rendering
display(HTML(df.to_html(escape=False, index=False)))
```

### Focus palette

The `focus` palette should be used to highlight specific elements of a plot.

The light grey colour in this palette does not have sufficient colour contrast against a white background and therefore this palette should only be used when it is essential to communicate your message. 
Follow the [advice for using the focus palette](https://analysisfunction.civilservice.gov.uk/policy-store/data-visualisation-colours-in-charts/#section-7) in the Government Analysis Function colour guidance when using this palette.



### Using your own colour palette

There may be instances where you'd like to use a different colour palette. 
If so, this should be carefully considered to ensure it meets accessibility requirements. 
The Government Analysis Function guidance outlines [appropriate steps for choosing your own accessible colour palette](https://analysisfunction.civilservice.gov.uk/policy-store/data-visualisation-colours-in-charts/#section-9) and should be used.

An example of how to use an alternative colour palette is provided in the [cookbook](https://best-practice-and-impact.github.io/afcharts/).
However, if you use a different palette regularly and feel it would be useful for this to be added to afcharts, please make a suggestion as per the [contributing guidance](https://best-practice-and-impact.github.io/afcharts/CONTRIBUTING.html).


### Things to consider when using colour

Using afcharts colour palettes does not guarantee that your charts will be accessible. 
The [Government Analysis Function](https://analysisfunction.civilservice.gov.uk/policy-store/data-visualisation-colours-in-charts/) has published guidance on other steps you should take to ensure the accessible use of colour.
afcharts should be used in conjunction with the advice given in these guidance documents.

The following are a few key things to consider when using colour in data visualisations:

*   Only use colour if absolutely necessary

*   Do not rely on colour alone to communicate a message

*   Use colour consistently when producing a series of plots

*   Limit the number of different colours you use; ideally an absolute maximum of four

*   Use colour palettes in the order presented to ensure adjacent colours have sufficient contrast with each other


### Viewing Palettes in Python

Names and hex codes for available colours and palettes can be viewed by running the following code:

```python
```

Examples of how to apply these palettes to ggplot2 charts are available in both the [cookbook](https://best-practice-and-impact.github.io/afcharts)