## Other customisations
## Sorting a bar chart

To control the order of bars in a bar chart, use the .sort_values() method on the data object before plotting. Pass the name or list of names that you would like to sort by and specify whether ascending (True, default) or descending (False). In this below example, the data is sorted on "pop" and ascending is set to True so that the bars are displayed in ascending order of population.


```{python}
#| output: false
import matplotlib.pyplot as plt
import plotly.express as px

# Load gapminder data from plotly
df = px.data.gapminder()

# Filter for Americas in 2007 and get top 5 by population
pop_bar_data = df[(df["year"] == 2007) & (df["continent"] == "Americas")]
pop_bar_data = pop_bar_data.nlargest(5, "pop").sort_values("pop", ascending=True) #Sort by population in ascending order

plt.style.use("afcharts.afcharts")

fig = plt.figure(figsize=(8, 5))
plt.barh(
    pop_bar_data["country"],
    pop_bar_data["pop"] / 1e6,  # Convert to millions
)

plt.gca().set_axisbelow(True) # Ensure gridlines appear at the back of the graph
plt.xlim(0, 300)
plt.xticks([0, 100, 200, 300])

plt.show()
```

<div class="chart-title">The U.S.A. is the most populous country in the Americas</div>

```{python}
#| echo: false

fig

```

<div class="chart-subtitle">Population of countries in the Americas (millions), 2007</div>
<div class="chart-source">Source: Gapminder</div>
<div class="chart-alt">
This bar chart uses the afcharts theme, and shows the populations of the five most populous countries in the Americas, sorted in ascending order by population. Each bar is dark blue and labelled by country underneath. All text is black in a sans serif font. Pale grey grid lines extend out from the y axis.
</div>

## Reducing space between chart and axis

You can adjust the padding between the ticks and the chart area using the .tick_params() method. Passing a value to the argument 'pad' will increase or decrease the space between the ticks and the chart area. In the below example, the padding is set to 6. This affects the values on both the x- and y-axes.

```{python}
# | output: false
import matplotlib.pyplot as plt

# Load gapminder dataset from plotly
from plotly.express.data import gapminder

# Set default theme
plt.style.use("afcharts.afcharts")

# Filter for Americas in 2007 and get top 5 by population
df = gapminder().query("year == 2007 & continent == 'Americas'")

top5 = df.nlargest(5, "pop")

fig = plt.figure()

plt.bar(
    top5["country"],
    top5["pop"] / 1e6,  # Convert to millions
)

plt.tick_params(pad=6) # Adjust padding between ticks and chart area

fig
```

<div class="chart-title">The U.S.A. is the most populous country in the Americas</div>
<div class="chart-subtitle">Population of countries in the Americas (millions), 2007</div>
<div class="chart" aria-describedby="barchart-1-desc">

```{python}
#| echo: false

fig

```

</div>
<div class="chart-source">Source: Gapminder</div>
<div class="chart-alt" id="barchart-1-desc">
This bar chart uses the afcharts theme, and shows the populations of the five most populous countries in the Americas. Each bar is dark blue and labelled by country underneath. All text is black in a sans serif font. Pale grey grid lines extend out from the y axis.
</div>

## Adding a horizontal or vertical line

To add a horizontal or vertical line across the whole plot, use axhline() or axvline() respectively. Annotating the line can be achieved using text(). This can be useful to highlight a threshold or average level.

```{python}
#| output: false
import matplotlib.pyplot as plt

# Load gapminder dataset from plotly
from plotly.express.data import gapminder

# Set default theme
plt.style.use("afcharts.afcharts")

df = gapminder().query("country == 'United Kingdom'")

# Make the figure wider than the default (6.4, 4.8)
fig = plt.figure(figsize=(8.5, 4.8))

plt.plot(df["year"], df["lifeExp"])

# Add a dotted horizontal line for 70 years of age
plt.axhline(y=70, linestyle='--', color='gray', linewidth=2)
plt.text(2005, 71, 'Age 70', fontsize=10, fontweight='normal', color='black')

plt.xlim([1950, 2010])
plt.ylim([0, 82])

fig
```

<div class="chart-title">Living Longer</div>
<div class="chart-subtitle">Life expectancy in the United Kingdom 1952 to 2007</div>
<div class="chart" aria-describedby="linechart-1-desc">

```{python}
#| echo: false

fig

```

</div>
<div class="chart-source">Source: Gapminder</div>
<div class="chart-alt" id="linechart-1-desc">
This line chart uses the afcharts theme. There are pale grey grid lines extending from the y axis, and there is a thicker dark blue line representing the data.
</div>